# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
import random
import requests, json
import gui
# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r".\res\frame1")
headers = {'Content-Type': 'application/json'}
url = 'https://authserver.mojang.com'


def authenticate(username: str, password: str, agentName: str = 'Minecraft', clientToken: str = None,
                 requestUser: str = False, authServer: str = url):
    data = json.dumps({"agent": {"name": agentName, "version": 1}, "username": username, "password": password,
                       "clientToken": clientToken, "requestUser": requestUser})
    response = json.loads(requests.post(authServer + '/authenticate', data=data, headers=headers, verify=False).text)
    if 'error' in response:
        raise Exception(f"{response['error']}: {response['errorMessage']}")
    else:
        return response


def auth():
    login = entry_2.get() + "@alt.me"
    passw = entry_1.get()
    if passw == "":
        with open('pas.json', "r") as fr:
            dictt = json.load(fr)
            passw = dictt["passw"]
            login = dictt["login"]
    else:
        with open('pas.json', "w") as fw:
            dicct = {
                "login": login,
                "passw": passw
            }
            fw.write(json.dumps(dicct))

    windowl.destroy()
    randomClientToken = random.randint(10000, 99999)
    mc = authenticate(login, passw, 'Minecraft', randomClientToken, False,
                      authServer='https://crossmine.ddns.net:443/authserver')
    accessToken = mc['accessToken']
    clientId = randomClientToken
    uuid = mc['selectedProfile']['id']
    nickname = mc['selectedProfile']['name']
    gui.go(accessToken, clientId, uuid, nickname)


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


windowl = Tk()
windowl.title("EventMod")
windowl.iconbitmap(r".\res\icon.ico")
from tkextrafont import Font

Font(file=r".\res\Jura.ttf", family="Regular")
Font(file=r".\res\UbuntuMono-Regular.ttf", family="Regular")
WIDTH = 1280
HEIGHT = 720
x = int((windowl.winfo_screenwidth() / 2) - (WIDTH / 2))
y = int((windowl.winfo_screenheight() / 2) - (HEIGHT / 2))
windowl.geometry(f'{WIDTH}x{HEIGHT}+{x}+{y}')
windowl.configure(bg="#BAB8FF")

bgcol = "#BAB8FF"

canvas = Canvas(
    windowl,
    bg="#BAB8FF",
    height=720,
    width=1280,
    bd=0,
    highlightthickness=0,
    relief="ridge"
)

canvas.place(x=0, y=0)
canvas.create_text(
    386.0,
    165.0,
    anchor="nw",
    text="EVENTMOD",
    fill="#747480",
    font=("Jura Regular", 110 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    activebackground=bgcol,
    bg=bgcol,
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: auth(),
    relief="flat"
)
button_1.place(
    x=523.00048828125,
    y=508.9800109863281,
    width=230.10009765625,
    height=54.600006103515625
)

canvas.create_text(
    614.0,
    284.0,
    anchor="nw",
    text="Логин",
    fill="#D4D4FD",
    font=("Ubuntu Mono", 23 * -1)
)

canvas.create_text(
    608.0,
    386.0,
    anchor="nw",
    text="Пароль",
    fill="#D4D4FD",
    font=("Ubuntu Mono", 23 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    640.56005859375,
    458.3000030517578,
    image=entry_image_1
)
entry_1 = Entry(
    font=("Ubuntu Mono", 20 * -1),
    bd=0,
    bg="#ADA6FB",
    fg="#E4E4FF",
    highlightthickness=0,
    insertontime=0
)
entry_1.place(
    x=432.3000030517578,
    y=431.0,
    width=416.5201110839844,
    height=52.600006103515625
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    640.340087890625,
    344.3000030517578,
    image=entry_image_2
)
entry_2 = Entry(
    font=("Ubuntu Mono", 20 * -1),
    bd=0,
    bg="#ADA6FB",
    fg="#E4E4FF",
    highlightthickness=0,
    insertontime=0
)
entry_2.place(
    x=431.3000030517578,
    y=317.0,
    width=418.0801696777344,
    height=52.600006103515625
)
windowl.resizable(False, False)
windowl.mainloop()
