# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
import requests
# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, filedialog, Toplevel

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r".\res\frame2")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


def skinset(skinvar, accessToken, windows, window):
    url = "https://crossmine.ddns.net/minecraftservices/minecraft/profile/skins"
    skinpath = filedialog.askopenfilename(defaultextension="png", filetypes=[("Skin image", ".png")])
    files = {'file': open(skinpath, 'rb')}
    headers = {
        'authorization': f"Bearer {accessToken}"
    }
    data = {
        'variant': skinvar
    }
    requests.request("POST", url, files=files, headers=headers, data=data, verify=False)
    window.deiconify()
    windows.destroy()


class go:
    def __init__(self, accessToken, window):
        def kill_root(windows=False, event=False, window=window):
            window.deiconify()

        windows = Toplevel()
        windows.title("EventMod")
        windows.iconbitmap(r".\res\icon.ico")
        windows.bind("<Destroy>", kill_root)
        WIDTH = 1280
        HEIGHT = 720
        x = int((windows.winfo_screenwidth() / 2) - (WIDTH / 2))
        y = int((windows.winfo_screenheight() / 2) - (HEIGHT / 2))
        windows.geometry(f'{WIDTH}x{HEIGHT}+{x}+{y}')
        windows.configure(bg="#BAB8FF")

        bgcol = "#BAB8FF"
        canvasl = Canvas(
            windows,
            bg="#BAB8FF",
            height=720,
            width=1280,
            bd=0,
            highlightthickness=0,
            relief="ridge"
        )

        canvasl.place(x=0, y=0)
        canvasl.create_text(
            381.820068359375,
            121.19998168945312,
            anchor="nw",
            text="EVENTMOD",
            fill="#747480",
            font=("Jura Regular", 110 * -1)
        )

        button_image_1l = PhotoImage(
            file=relative_to_assets("button_1.png"))
        button_1l = Button(
            master=windows,
            activebackground=bgcol,
            bg=bgcol,
            image=button_image_1l,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: skinset("slim", accessToken, windows, window),
            relief="flat"
        )
        button_1l.place(
            x=294.4599609375,
            y=299.8199462890625,
            width=193.43994140625,
            height=304.98004150390625
        )

        button_image_2l = PhotoImage(
            file=relative_to_assets("button_2.png"))
        button_2l = Button(
            master=windows,
            activebackground=bgcol,
            bg=bgcol,
            image=button_image_2l,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: skinset("default", accessToken, windows, window),
            relief="flat"
        )
        button_2l.place(
            x=792.10009765625,
            y=299.8199768066406,
            width=193.43994140625,
            height=304.9800720214844
        )

        canvasl.create_text(
            468.0,
            254.0,
            anchor="nw",
            text="Выберите вариант скина",
            fill="#D3D3FC",
            font=("Ubuntu Mono", 31 * -1)
        )
        windows.resizable(False, False)
        windows.mainloop()
