debug = false
disable_crowdin = false
check_for_updates = true

[activations.4aec07ba-d109-3345-9a0a-92022a116cd0]
toggle = false
type = "VOICE"
[[key_bindings]]
name = "key.plasmovoice.general.mute_microphone"
any_context = false
category = "key.plasmovoice.general"

[[key_bindings.keys]]
code = 342
type = "KEYSYM"



[voice]
disabled = false
microphone_disabled = false
activation_threshold = -30.0
input_device = ""
output_device = ""
disable_input_device = false
use_javax_input = false
microphone_volume = 1.0
noise_suppression = false
volume = 1.0
compressor_limiter = true
sound_occlusion = false
directional_sources = false
hrtf = true
stereo_capture = false

[voice.volumes.source_23f279dc-0ed9-4af7-a788-3f564bc6ff42]
volume = 1.0
[voice.volumes.source_4e7474cf-6561-4937-a2ba-c0b1e336e98a]
volume = 1.0
[voice.volumes.source_757d8a65-77ab-4128-bb75-393d984489f9]
volume = 1.0
[voice.volumes.source_990b4f5a-eddd-4566-98cb-e203fad9e142]
volume = 1.0
[voice.volumes.source_4b165359-2074-4e42-ad52-3804a1055c66]
volume = 1.0
[voice.volumes.proximity]
volume = 1.0
[voice.volumes.source_cea4d0e8-ebae-4997-9655-2fdd8e85fa57]
volume = 1.0
[voice.volumes.source_c9dbea93-3608-4364-8402-2dd0e5059a9a]
volume = 1.0
[voice.volumes.source_ecd29f02-af7b-4f3a-a3c2-09515f86f0cc]
volume = 1.0
[voice.volumes.source_fbcba370-0c0a-4a3c-aa4d-c3e5ec942b6c]
volume = 1.0
[voice.volumes.source_ab7e6607-62a3-4e11-b5d5-3038af8fcaad]
volume = 1.0
[voice.volumes.source_2f273f1e-4ad3-47f5-a5f9-c24c6c476c05]
volume = 1.0

[advanced]
visualize_voice_distance = true
visualize_voice_distance_on_join = false
compressor_threshold = -10
limiter_threshold = -6
directional_sources_angle = 145
stereo_sources_to_mono = false
panning = true
camera_sound_listener = true
exponential_volume_slider = true
exponential_distance_gain = true

[overlay]
show_activation_icon = true
activation_icon_position = "BOTTOM_CENTER"
show_source_icons = 0
show_static_source_icons = true
overlay_enabled = true
overlay_position = "TOP_LEFT"
overlay_style = "NAME_SKIN"

[overlay.source_states]
proximity = "OFF"
